[build-system]
requires = ["setuptools", "wheel", "Cython", 'pyarrow>=2.0.0','numpy>=1.19.0','python-snappy>=0.5.4']
build-backend = "setuptools.build_meta"
[project]
dependencies = [
    'pyarrow>=3.0.0',
    'fastavro>=1.0.0.post1',
    'numpy>=1.19.0'
]
